name: Benchmark vectorized vs. consolidated writes

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "ubuntu-latest"
          - "ubuntu-24.04-arm"
          - "macos-latest" # arm
          - "macos-13" # x86_64
          - "windows-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install CMake 3.31
        if: matrix.platform != 'ubuntu-24.04-arm'
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.31.x"

      - name: Install CMake 3.31 for ARM
        if: matrix.platform == 'ubuntu-24.04-arm'
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-linux-aarch64.tar.gz
          tar -xzf cmake-3.31.8-linux-aarch64.tar.gz
          sudo mv cmake-3.31.8-linux-aarch64 /opt/cmake
          echo "/opt/cmake/bin" >> $GITHUB_PATH

      - name: Configure and build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20
          cmake --build build --config Release

      - name: Run benchmarks
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          ./build/vectorized_test
          mv -f results.csv results-${{ matrix.platform }}.csv

      - name: Run benchmarks on Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          .\build\Release\vectorized_test.exe

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark-results-${{ matrix.platform }}
          path: results.csv

  consolidate:
    name: Consolidate benchmark results into a single zip
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Download benchmark results
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results-ubuntu-latest
      - name: Consolidate results
        run: |
          mkdir consolidated_results
          for file in results-*.csv; do
          cp "$file" consolidated_results/
          done
      - name: Zip consolidated results
        run: |
          zip -r consolidated_results.zip consolidated_results

      - name: Upload consolidated results
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-benchmark-results
          path: consolidated_results.zip
